[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[context.production.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium", "puppeteer-core"]

# Redirects
[[redirects]]
  from = "/"
  to = "/ja/"
  status = 302

[[redirects]]
  from = "/*"
  to = "/ja/index.html"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/yuta-hidaka-resume-english.pdf"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/yuta-hidaka-resume-japanese.pdf"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
