[build]
command = "bun run build"
publish = ".next"

[build.environment]
BUN_VERSION = "1.2.14"

[[plugins]]
package = "@netlify/next"

[dev]
command = "bun run dev"
framework = "next"
targetPort = 3000
port = 8888
